package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"iter"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

func TestFetchTimeoutsMatchPython(t *testing.T) {
	// Generated by the original iter_tout with random.random() == 0.5.
	want := []int{60, 90, 135, 202, 303, 455, 683, 1025, 1537, 2306, 3459, 5189, 7784, 10000, 10000}
	next, stop := iter.Pull(fetchTimeouts(func() float64 { return 0.5 }))
	defer stop()
	for i, seconds := range want {
		got, _ := next()
		if got != time.Duration(seconds)*time.Second {
			t.Fatalf("attempt %d: timeout=%s, want %ds", i, got, seconds)
		}
		if got := fetchConnectTimeout(got); got != time.Duration(seconds/10)*time.Second {
			t.Fatalf("attempt %d: connect timeout=%s", i, got)
		}
	}
	for _, tc := range []struct {
		random        float64
		first, capped int
	}{
		{0, 30, 5000}, {0.999999, 89, 14999},
	} {
		next, stop := iter.Pull(fetchTimeouts(func() float64 { return tc.random }))
		first, _ := next()
		var capped time.Duration
		for i := 0; i < 20; i++ {
			capped, _ = next()
		}
		stop()
		if first != time.Duration(tc.first)*time.Second || capped != time.Duration(tc.capped)*time.Second {
			t.Fatalf("random=%g: first=%s capped=%s", tc.random, first, capped)
		}
	}
}

func TestFetchSourceDictAndSnapshot(t *testing.T) {
	sha := strings.Repeat("a", 64)
	s := newFetchSources("origin", sha, []string{"a/{one}/{two}/{sha}", "origin", "a/{one}/{two}/{sha}", "b"})
	want := []string{"a/a/aa/" + sha, "origin", "b"}
	if !reflect.DeepEqual(s.order, want) || s.good["origin"].cache {
		t.Fatalf("sources=%+v", s)
	}
	next, stop := iter.Pull(s.urls())
	defer stop()
	first, _ := next()
	delete(s.good, first.url)
	delete(s.good, "b")
	second, _ := next()
	third, _ := next() // Already in the current snapshot, despite deletion.
	fourth, _ := next()
	if second.url != "origin" || third.url != "b" || fourth.url != "origin" {
		t.Fatalf("snapshot order: %v %v %v", second, third, fourth)
	}
	delete(s.good, "origin")
	if _, ok := next(); ok {
		t.Fatal("sources did not terminate")
	}
	for _, sha := range []string{"__skip__", "short", strings.Repeat("1", 64)} {
		s := newFetchSources("origin", sha, []string{"mirror"})
		if !reflect.DeepEqual(s.order, []string{"origin"}) {
			t.Fatal(s.order)
		}
	}
}

func TestFetchZipsRoutesAndURLsWithoutReset(t *testing.T) {
	body := []byte("artifact")
	sha := fmt.Sprintf("%x", sha256.Sum256(body))
	path := filepath.Join(t.TempDir(), "out", "file")
	type attempt struct {
		url, proxy string
		seconds    int
	}
	var got []attempt
	f := fetcher{random: func() float64 { return 0.5 }, log: io.Discard}
	f.download = func(url, path, proxy string, timeout time.Duration) {
		got = append(got, attempt{url, proxy, int(timeout / time.Second)})
		if _, err := os.Stat(filepath.Join(filepath.Dir(path), "partial")); !os.IsNotExist(err) {
			t.Fatal("previous attempt's directory was not cleaned")
		}
		Throw(os.WriteFile(filepath.Join(filepath.Dir(path), "partial"), nil, 0600))
		switch len(got) {
		case 1:
			ThrowFmt("The requested URL returned error: 404")
		case 2:
			Throw(os.WriteFile(path, []byte("bad mirror"), 0600))
		case 3, 4, 5:
			ThrowFmt("temporary network error")
		case 6:
			Throw(os.WriteFile(path, body, 0600))
		default:
			t.Fatal("unexpected retry")
		}
	}
	f.fetch("origin", path, sha, []string{"a", "b", "a", "b", "a", "b"}, " p1 ; ; p2; ")
	want := []attempt{{"a", "p1", 60}, {"b", "p2", 90}, {"origin", "", 135}, {"origin", "p1", 202}, {"origin", "p2", 303}, {"origin", "", 455}}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("got=%v want=%v", got, want)
	}
}

func TestFetchTerminalErrorsAndRetries(t *testing.T) {
	for _, tc := range []struct {
		name, failure string
		wantCalls     int
		wantError     string
	}{
		{"404", "error: 404", 2, "no sources left"},
		{"checksum", "checksum mismatch", 2, "checksum mismatch"},
		{"403 stays", "error: 403", 25, ""},
		{"500 stays", "error: 500", 25, ""},
		{"timeout stays", "deadline exceeded", 25, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			body := []byte("ok")
			sha := fmt.Sprintf("%x", sha256.Sum256(body))
			calls := 0
			randomCalls := 0
			f := fetcher{random: func() float64 { randomCalls++; return 0.5 }, log: io.Discard}
			f.download = func(url, path, proxy string, timeout time.Duration) {
				calls++
				if calls > tc.wantCalls {
					t.Fatal("unexpected extra attempt")
				}
				if tc.wantError == "" && calls == tc.wantCalls {
					Throw(os.WriteFile(path, body, 0600))
					return
				}
				ThrowFmt("%s", tc.failure)
			}
			err := Try(func() { f.fetch("origin", filepath.Join(t.TempDir(), "out", "file"), sha, []string{"mirror"}, "p1;p2") })
			if calls != tc.wantCalls || randomCalls != calls {
				t.Fatalf("calls=%d random=%d", calls, randomCalls)
			}
			if tc.wantError == "" && err != nil {
				t.Fatal(err)
			}
			if tc.wantError != "" && (err == nil || !strings.Contains(err.Error(), tc.wantError)) {
				t.Fatalf("error=%v", err)
			}
		})
	}
}

func TestFetchSHAAndPrepare(t *testing.T) {
	path := filepath.Join(t.TempDir(), "out", "file")
	prepareFetchDir(path)
	Throw(os.WriteFile(path, []byte("ok"), 0600))
	checkFetchSHA(path, fmt.Sprintf("%x", sha256.Sum256([]byte("ok"))))
	checkFetchSHA("missing", "prefix__skip__suffix")
	if err := Try(func() { checkFetchSHA(path, strings.Repeat("1", 64)) }); err == nil || !strings.Contains(err.Error(), "checksum") {
		t.Fatal(err)
	}
	prepareFetchDir("bare-file")
	for _, path := range []string{"/file", "./file"} {
		if err := Try(func() { prepareFetchDir(path) }); err == nil {
			t.Fatalf("unsafe path accepted: %s", path)
		}
	}
	root := t.TempDir()
	Throw(os.Symlink(filepath.Dir(path), filepath.Join(root, "link")))
	if err := Try(func() { prepareFetchDir(filepath.Join(root, "link", "file")) }); err == nil {
		t.Fatal("symlink accepted")
	}
	if got := Throw2(os.ReadFile(path)); !bytes.Equal(got, []byte("ok")) {
		t.Fatal("symlink target damaged")
	}
}
